### PR TITLE
Fix installation errors on mac/linux

### PR DESCRIPTION
**Pull request by vi4m**
Excluded arm related files which causes errors:
* filter_neon_intrinsics.c.o) has no symbols
* libCpng.a(arm_init.c.o) has no symbols

Also, removed pngtest.c file from list  which caused:
* duplicate symbol _main in: pngtest.c.o and [your app code] when used
C extensions.

### CODE REVIEW

**Comment by s1ddok** [comment]
While I agree with `pngtest.c` removal (it was probably added by mistake), I don't think removing arm files without conditiolizing builds is a good idea since I use this package for Android build as well. 

No symbols warnings are something I can get away with, I think

**Comment by vi4m** [comment]
Does SPM support Android builds? wow :-) 

I guess i can live with these 2 warnings, so i can add this 2 files back. Or can we conditionalize build in the other way?

**Comment by vi4m** [comment]
So if you don't need this pngtest.c - maybe we remove it from repository?

**Comment by vi4m** [comment]
Here's an update to just remove this file from repository, leaving the rest untouched.

**Comment by s1ddok** [comment]
Cool, thanks for cleaning up the tree. I will look at how we can conditionlize builds. Environmental variables are probably the way to go here, until build settings officially released in SwiftPM.

**Pull request merged**
